FROM golang:1.24-alpine AS build
WORKDIR /src

# Needed for CGO + go-sqlite3
RUN apk add --no-cache git ca-certificates build-base

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=1 go build -o /out/jetqueue-api ./cmd/api

FROM alpine:3.20
RUN apk add --no-cache ca-certificates sqlite-libs
WORKDIR /app
COPY --from=build /out/jetqueue-api /app/jetqueue-api
EXPOSE 50051 2112
ENTRYPOINT ["/app/jetqueue-api"]